# Generated by Django 3.1.4 on 2020-12-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorylist',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryId', primary_key=True, serialize=False)),
                ('categoryname', models.TextField(db_column='categoryName', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('itemid', models.AutoField(db_column='itemId', primary_key=True, serialize=False)),
                ('itemtitle', models.TextField(db_column='itemTitle')),
                ('itemdescription', models.TextField(db_column='itemDescription')),
                ('categoryid', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.DO_NOTHING, to='texts.categorylist')),
            ],
        ),
    ]
