# Generated by Django 3.1.4 on 2020-12-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0002_auto_20201212_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='categoryid',
            field=models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.DO_NOTHING, to='texts.categorylist'),
        ),
    ]
